[package]
name = "strange"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.17.3", features = ["bevy_debug_stepping", "dynamic_linking"] }
bevy_ecs = "0.17.3"

[profile.dev]
opt-level =1

[profile.dev.package."*"]
opt-level = 3
